doc/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import (
    doc_home,
    doc_detail,
    doc_create,
    doc_update,
    doc_delete,
    doc_about,
    doc_contact,
    doc_registru
)


urlpatterns = [
    url(r'^$', doc_home, name='home'),
    url(r'^about/$', doc_about, name='about'),
    url(r'^registru/$', doc_registru, name='registru'),
    url(r'^contact/$', doc_contact, name='contact'),
    url(r'^(?P<id>\d+)/$', doc_detail, name='detail'),
    url(r'^create/$', doc_create, name='create'),
    url(r'^(?P<id>\d+)/edit/$', doc_update, name='update'),
    url(r'^(?P<id>\d+)/delete/$', doc_delete, name='delete'),
]

registru/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^doc/', include("doc.urls", namespace='doc')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doc/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.forms import ModelForm
from django.core.urlresolvers import reverse

# Create your models here.
STATUS_CHOICES = (
    ('Dreapta', 'Dreapta'),
    ('Stanga', 'Stanga'),
)

STATUS_CHOICES_DRDP = (
    ('Bucuresti', 'Bucuresti'),
    ('Craiova', 'Craiova'),
    ('Timisoara', 'Timisoara'),
    ('Cluj', 'Cluj'),
    ('Brasov', 'Brasov'),
    ('Iasi', 'Iasi'),
    ('Constanta', 'Constanta'),
)

def upload_location(instance, filename):
    return '%s/%s' %(instance.id, filename)


class Doc(models.Model):
    title               = models.TextField()
    image               = models.FileField(upload_to=upload_location, null=True, blank=True)    
    nrDoc               = models.IntegerField()
    dataDoc             = models.DateField()
    emitent             = models.CharField(max_length=100)
    beneficiar          = models.CharField(max_length=100)
    drumulNational      = models.CharField(max_length=10)
    pozitiaKilometrica  = models.CharField(max_length=50)
    partea              = models.CharField(max_length=7, null=True, blank=True,choices=STATUS_CHOICES)
    drdp                = models.CharField(max_length=10, null=True, blank=True,choices=STATUS_CHOICES_DRDP)
    creat               = models.DateTimeField(auto_now=False, auto_now_add=True)
    modificat           = models.DateTimeField(auto_now=True, auto_now_add=False)
    rezolvat            = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_absolut_url(self):
        return reverse("doc:detalii", kwargs={'id': self.id})
        #return "/document/%s/" %(self.id)

    class Meta:
        ordering = ['-creat', '-modificat']

doc/forms.py
from django import forms

from .models import Doc

class DocForm(forms.ModelForm):
    class Meta:
        model = Doc
        fields = [
            'title',
            'nrDoc',
            'dataDoc',
            'emitent',
            'beneficiar',
            'drumulNational',
            'partea',
            'drdp',
            'image',
            'rezolvat',
        ]

doc/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect

from .forms import DocForm
from .models import Doc

# Create your views here.
def doc_registru(request):
    queryset = Doc.objects.all()
    context = {
        'object_list': queryset,
        'title': 'Registru'
    }
    return render(request, "registru.html", context)

def doc_home(request):
    context = {
        'title': 'Home'
    }
    return render(request, "doc_home.html", context)

def doc_about(request):
    context = {
        'title': 'About'
    }
    return render(request, "about.html", context)

def doc_contact(request):
    context = {
        'title': 'Contact'
    }
    return render(request, "contact.html", context)

def doc_detail(request):
    context = {
        'title': 'Detail'
    }
    return render(request, "doc_detail.html", context)

def doc_create(request):
    form = DocForm(request.POST or None, request.FILES or None)
    context = {
        'form': form
    }
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request,'Succesfully created')
        return HttpResponseRedirect(instance.get_absolut_url())

    return render(request, "doc_create.html", context)

def doc_update(request):
    context = {
        'title': 'Update'
    }
    return render(request, "doc_update.html", context)

def doc_delete(request):
    context = {
        'title': 'Delete'
    }
    return render(request, "doc_delete.html", context)

templates/about.html
{% extends "base.html" %} {% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Registru de intrări / ieșiri</h1>
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
    </div>
</section>
{% endblock content %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Starter Template for Bootstrap 3.3.6 Documentation - BootstrapDocs</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="starter-template.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

    {% include "navbar.html" %}

    <div class="container-fluid">

        {% block content %} {% endblock content %}
        <!--
        <div class="starter-template">
            <h1>Bootstrap starter template</h1>
            <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
        </div>
    -->

    </div>
    <!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'javascript/jquery.min.js' %}"></script>
    <script>
        window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')
    </script>
    <script src="{% static 'javascript/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'javascript/ie10-viewport-bug-workaround.js' %}"></script>
</body>

</html>

templates/contact.html
{% extends "base.html" %} {% block content %}
<h1>Welcome to Contact page!!!</h1>
{% endblock content %}

templates/doc_create.html
{% extends "base.html" %} {% block content %}
<h1>hello doc_create</h1>
{% endblock content %}

templates/doc_delete.html
{% extends "base.html" %} {% block content %}
<h1>hello doc_delete</h1>
{% endblock content %}

templates/doc_detail.html
{% extends "base.html" %} {% block content %}
<h1>hello doc_detail</h1>
{% endblock content %}

templates/doc_home.html
{% extends "base.html" %} {% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Registru de intrări / ieșiri</h1>
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
        <p>
            <a href="{% url 'doc:registru' %}" class="btn btn-primary my-2">Listă intrări</a>
            <a href="{% url 'doc:create' %}" class="btn btn-secondary my-2">Adaugă intrare</a>
        </p>
    </div>
</section>
{% endblock content %}

templates/doc_update.html
{% extends "base.html" %} {% block content %}
<h1>hello doc_update

</h1>
{% endblock content %}

templates/nav.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{% url 'doc:registru' %}">Registru</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'doc:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'doc:about' %}">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="{% url 'doc:contact' %}">Contact</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

templates/navbar.html
<nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <!-- <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search"> -->
      </button>
            <a class="navbar-brand" href="{% url 'doc:registru' %}">Registru</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'doc:home' %}">Home</a></li>
                <li><a href="{% url 'doc:about' %}">About</a></li>
                <li><a href="{% url 'doc:contact' %}">Contact</a></li>
            </ul>
            <div id="custom-search-input">
                <div class="input-group col-md-2">
                    <input type="text" class="  search-query form-control" placeholder="Search" />
                    <span class="input-group-btn">
                                <button class="btn btn-danger" type="button">
                                    <span class=" glyphicon glyphicon-search"></span>
                    </button>
                    </span>
                </div>
            </div>


        </div>

        <!--/.nav-collapse -->
    </div>
</nav>

templates/registru.html
{% extends "base.html" %} {% block content %}

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Titlu</th>
            <th scope="col">NrDoc</th>
            <th scope="col">DataDoc</th>
            <th scope="col">Emitent</th>
            <th scope="col">Beneficiar</th>
            <th scope="col">DN</th>
            <th scope="col">PozKilom</th>
            <th scope="col">Partea</th>
            <th scope="col">DRDP</th>
            <th scope="col">Creat</th>
        </tr>
    </thead>
    <tbody>
        {% for obj in object_list %}
        <tr>

            <th scope="row">{{ obj.id }}</th>
            <td>
                <div style="width:200px; word-wrap: break-word">{{ obj.title }}</div>
            </td>
            <td>{{ obj.nrDoc }}</td>
            <td>{{ obj.dataDoc }}</td>
            <td>{{ obj.emitent }}</td>
            <td>{{ obj.beneficiar }}</td>
            <td>{{ obj.drumulNational }}</td>
            <td>{{ obj.pozitiaKilometrica }}</td>
            <td>{{ obj.partea }}</td>
            <td>{{ obj.drdp }}</td>
            <td>{{ obj.creat }}</td>

        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content%}